export const dataPointMetaData = [
  {
    name: "applicant_id",
    fieldType: "string",
    dataType: "Integer",
    key: "applicant_id", // Added key,
    man: 1,
  },
  {
    name: "Credit_Score",
    fieldType: "inputNumber",
    dataType: "Integer",
    range: { from: 300, to: 900 },
    key: "credit_score", // Added key,
    man: 1,
  },
  {
    name: "Self_Reported_Expenses",
    fieldType: "inputNumber",
    dataType: "Float",
    range: { from: 0, to: 10000 },
    key: "self_reported_expenses", // Added key,
    man: 1,
  },
  {
    name: "Annual_Income",
    fieldType: "inputNumber",
    dataType: "Float",
    range: { from: 20000, to: 250000 },
    key: "annual_income", // Added key,
    man: 1,
  },
  {
    name: "Self_Reported_Debt",
    fieldType: "inputNumber",
    dataType: "Float",
    range: { from: 0, to: 50000 },
    key: "self_reported_debt", // Added key,
    man: 1,
  },
  {
    name: "Requested_Amount",
    fieldType: "inputNumber",
    dataType: "Float",
    range: { from: 1000, to: 50000 },
    key: "requested_amount", // Added key,
  },
  {
    name: "Age",
    fieldType: "inputNumber",
    dataType: "Integer",
    range: { from: 19, to: 100 },
    key: "age", // Added key
  },
  {
    name: "Province",
    fieldType: "select",
    dataType: "string",
    options: [
      { value: 1, label: "Ontario" },
      { value: 2, label: "Quebec" },
      { value: 3, label: "British Columbia" },
      { value: 4, label: "Alberta" },
      { value: 5, label: "Manitoba" },
      { value: 6, label: "Saskatchewan" },
      { value: 7, label: "Nova Scotia" },
      { value: 8, label: "New Brunswick" },
      { value: 9, label: "Newfoundland and Labrador" },
      { value: 10, label: "Prince Edward Island" },
      { value: 11, label: "Northwest Territories" },
      { value: 12, label: "Nunavut" },
      { value: 13, label: "Yukon" },
    ],
    key: "province", // Added key
  },
  {
    name: "Employment_Status",
    fieldType: "select",
    dataType: "string",
    options: [
      { value: 2, label: "Full-Time" },
      { value: 1, label: "Part-Time" },
      { value: 0, label: "Unemployed" },
    ],
    key: "employment_status", // Added key,
    man: 1,
  },
  {
    name: "Months_Employed",
    fieldType: "inputNumber",
    dataType: "Integer",
    range: { from: 0, to: 600 },
    key: "months_employed", // Added key,
    man: 1,
  },
  {
    name: "Credit_Utilization",
    fieldType: "inputNumber",
    dataType: "Float",
    range: { from: 0, to: 100 },
    key: "credit_utilization", // Added key,
    man: 1,
  },
  {
    name: "Num_Open_Accounts",
    fieldType: "inputNumber",
    dataType: "Integer",
    range: { from: 0, to: 50 },
    key: "num_open_accounts", // Added key,
    man: 1,
  },
  {
    name: "Num_Credit_Inquiries",
    fieldType: "inputNumber",
    dataType: "Integer",
    range: { from: 0, to: 30 },
    key: "num_credit_inquiries", // Added key
  },
  {
    name: "Payment_History",
    fieldType: "select",
    dataType: "string",
    options: [
      { value: 3, label: "On Time" },
      { value: 2, label: "Late<30" },
      { value: 1, label: "Late 30-60" },
      { value: 0, label: "Late>60" },
    ],
    key: "payment_history", // Added key,
    man: 1,
  },
  {
    name: "Current_Credit_Limit",
    fieldType: "inputNumber",
    dataType: "Float",
    range: { from: 1000, to: 500000 },
    key: "total_credit_limit", // Added key,
    man: 1,
  },
];
